# Generated by Django 2.0.9 on 2018-11-22 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("catalogue", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="productstock",
            name="product_attribute_value",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_product_attribute_value",
                to="catalogue.ProductAttributeValue",
                verbose_name="Stock of Specific Value of the Product",
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="sold",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="products sold"
            ),
        ),
    ]
